# Recep Tayyip Erdogan - 20170808039 - Exercise 1


## Exercise 1.1 The interpreter

a) The output of 3 + 1 will be 4 in interpreter
b) The output of 3 * 3 will be 9 in interpreter
c) The output of 2 ** 3 will be 8 in interpreter, because it takes 3rd power of 2 
d) The output of "Hello, world!" will be Hello, world! in interpreter.

## Exercise 1.2 Scripts

I wrote the above codes to the script but nothing return. Because we need to use print() function to display outputs. 

## Exercise 1.3 More interpreter

a) This statement will give output "python" word because interpreter directly sum these two string.
b) Output will be "pypypython". Because interpreter will print the "py" three times.
c) Interpreter gives the type error:  "unsupported operand types for string".
d) Interpreter gives the type error: "can only concatenate string(not int)"
e) The output will be 333 as a string. Just multiply string with 3.
f) It gives Name Error: "a is not defined". Because we didnt define and initialize any value.
g) Output will be nothing but statement is okey for interpreter.
h) Output will be 3 after the above statement. Because a is a variable and initialized with 3.

## Exercise 1.4 Booleans

a) The interpreter returns true.
b) The interpreter returns true.
c) The interpreter returns false. Because 0 is equals to the false.
d) The interpreter returns true. As i said above statement; Zero equals to False.
e) The interpreter returns true. Because two side of the statements are equals each other.
f) The interpreter returns 0. Because 3 == 1 is false and it's value equals to the 0. Than multiply 3 with 0 so the final value will be 0.
g) The interpreter returns false. Because the statement of 3 == 3 is True and equals to the 1. Than multiply with 4 so equals to the 4 and sum with 3 and left side's equalt to 7 but right side equals to the 1 so statement is false.
h) It returns false. because left side of the statement is equals to the 243 and right side is 256 so the right side greater than left side. 

## Exercise 1.5: Integers

a) It returns 1.6666666666666667 as a float. Because The division of 2 integer will produce a float in python 3.
b) It returns 2 because when you divide 5 by 3 reminder is equals to 2
c) It returns 1.6666666666666667. Because 5.0 is a float value and final value will be also float value.
d) It returns 1.6666666666666667. Because 3.0 is a float value and final value will be also float value.
e) It returns 2.2. When you divide the 5.2 by 3 the remainder will be 2. Interpreter do the samething exactly.
f) It returns very huge value: 
1775896810483121914350934797871501063452843428843794422323202530887281536545210629921129898113201749875234297340507804201761453596034016264189501186924066128377025843892373608427790859511135990682732202975330824797118808624727351608183194154557208730494440110429635650057431833674286462463508755276302896154336475782768613964332764108132533925570342220340698973761380541294970139762186212823359128790706292900765512137078550033912252338262922477518858757114840012576514724742388124595061301502222934806074032688691170880996881967426442947828261057852871032366879179996122216385870273020506079240103910728766397733398071775041745854959302025036249707279600400001

Because the statement means that: Multiply 2001 with itself in 200 times.

## Exercise 1.6: Floats

a) It exceed the limit of number. It returns the OverflowError. 
b) It returns 1.0 because 2.0 - 1.0 will be 1.0.
c) It returns 0.0. Because: 1 + 1.0e20 equals to the 1e+20 so the output will be 0.

## Exercise 1.7: Variables

In [94]:
name = "John Doe"
x = "Hello, "
y = "!"
x + name + y

'Hello, John Doe!'

## Exercise 1.8: Type casting

a) It gives the 123.0 as a output because float method will turn the string to the float number.

In [95]:
x = "123"
float(x)

123.0

b) It gives the 123.0 as a output because float method will turn the string to the float number.

In [96]:
float("123")

123.0

c) It gives the 123.23. The float method turns the value as a number.

In [97]:
float("123.23")

123.23

d) It gives us to 123 because the string is a float but int method do the type casting and return the integer number.

In [98]:
int(123.23)

123

e)It gives the Value error. Because the string is a float number so before the turn integer we should do type casting to return number type.

In [99]:
int("123.23")

ValueError: invalid literal for int() with base 10: '123.23'

f) It gives us 123 value because float number will type casting and the string will be 123.23 then integer method will do type casting and we get the 123 value.

In [ ]:
int(float("123.23"))

g) It will do type casting and number return to the string "12";

In [ ]:
str(12)

h) The value will return the 12.2 as a string value.

In [ ]:
str(12.2)

i) It gives us the true. Bool method return the value as a boolean value. It gives true because all value return true except 0.

In [ ]:
bool("a")

j) It gives False value. Because 0 is accepted as a false in Python.

In [ ]:
bool(0)

k) It gives the True value. Except 0 all numbers value accepted as a True in python.

In [ ]:
bool(0.1)

# Exercise 2.1: Range

The following code's output will be range(0,5). It means the value starts from 0 to 5, 5 is not inclusive. Also for i in range(5) means that i starts from 0 and go to the 5  and 5 is not inclusive.

In [ ]:
range(5) 

In [ ]:
type(range(5)) 

Above statement returns the range value. It means range is an range type.

## Exercise 2.2: For loops

In [100]:
# Exercise 2.2 a) The Following loop will print the numbers from 0 to 100
for i in range(101):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [101]:
# Exercise 2.2 b) The following code will print the all number divisible by 7 range(101)
for i in range(101):
    if(i % 7 == 0):
        print(i)


0
7
14
21
28
35
42
49
56
63
70
77
84
91
98


In [102]:
# Exercise 2.2 c) The following code will print the all numbers divisible by 5 not 3 in range(101)
for i in range(101):
    if( i % 5 == 0 and i % 3 != 0):
        print(i)

5
10
20
25
35
40
50
55
65
70
80
85
95
100


In [103]:
# Exercise 2.2 d) The following code will the all divisible elements for number variable.
number = 20
for i in range(2, number):
    if(number % i == 0 ):
        print(i)



2
4
5
10


Exercise 2.3: Simple while loops

In [104]:
# Exercise 2.3 a)The following loop print the numbers from 0 to 100
i = 0
while i < 100:
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [105]:
# Exercise 2.3 b) The following loop print the numbers from 0 to 100 divisible by 7
i = 0
while i <= 100:
    if i % 7 == 0:
        print(i)
    i = i+1

0
7
14
21
28
35
42
49
56
63
70
77
84
91
98


## Exercise 2.4: Hangman update 1

## Exercise 2.5: While loops 

In [106]:
numberOfDivisible = 0
i = 1
while numberOfDivisible < 20:
    if i % 5 == 0 and i % 7 == 0 and i % 11 == 0:
        print(i)
        numberOfDivisible = numberOfDivisible + 1
    i = i+1

print("Number Of divisible found: " + str(numberOfDivisible))

385
770
1155
1540
1925
2310
2695
3080
3465
3850
4235
4620
5005
5390
5775
6160
6545
6930
7315
7700
Number Of divisible found: 20


## Exercise 2.6: More while loops

In [107]:
x = 1
control = False
while control is not True:
    j = 1
    while j < 11:
        if x % j == 0:
            if j == 10:
                control = True
                print(x)
        else:
            break
        j = j + 1
    x = x + 1    

2520


## Exercise 2.7: Collatz sequence

In [108]:
initialization = 103
print(initialization)
while True:
    if(initialization == 1):
        break
    elif(initialization % 2 == 0):
        initialization = initialization / 2
        print(int(initialization))
    else:
        initialization = initialization * 3 + 1
        print(int(initialization))


103
310
155
466
233
700
350
175
526
263
790
395
1186
593
1780
890
445
1336
668
334
167
502
251
754
377
1132
566
283
850
425
1276
638
319
958
479
1438
719
2158
1079
3238
1619
4858
2429
7288
3644
1822
911
2734
1367
4102
2051
6154
3077
9232
4616
2308
1154
577
1732
866
433
1300
650
325
976
488
244
122
61
184
92
46
23
70
35
106
53
160
80
40
20
10
5
16
8
4
2
1


# **3 Functions** 

## Exercise 3.1: Hello

In [109]:
# Exercise 3.1 a) Write a function hello_world that prints ’Hello, world!’

def hello_world():
    print("Hello, world!")

if __name__ == "__main__":
    hello_world()

Hello, world!


In [110]:
# Exercise 3.1 b) Write a function hello_name(name) that prints ’Hello, name!’ where name is a string.

def hello_world(name):
    print("Hello, " + name + "!")
if __name__ == "__main__":
    hello_world("Recep")

Hello, Recep!


Exercise 3.1 c) Explain the difference between the print and return keywords. What would change if instead of
print you would use return?

Answer: While print just writes the parameter thats given to terminal, return keyword assigns the given variable to the corresponding variable.

## Exercise 3.2: Polynomial

In [111]:
def polinomial(x):
    return (3*x**2) - x + 2
if __name__ == "__main__":
    print(polinomial(5))

72


## Exercise 3.3: Maximum

In [112]:
# Exercise 3.3: Maximum a)

def my_max(x, y):
    if x > y:
        return x
    else:
        return y

if __name__ == "__main__":
    print(my_max(5 , 3))

5


In [113]:
# Exercise 3.3: Maximum b)

def my_max(x, y):
    if x > y:
        return x
    if y > x:
        return y

if __name__ == "__main__":
    print(my_max(5 , 3))

5


## Exercise 3.4: Primes

In [114]:
# Exercise 3.4: Primes a)
def is_prime(n):
    counter = 2
    while counter < n:
        if n % counter == 0:
            return False
        counter += 1
    return True
        
if __name__ == "__main__":
    print(is_prime(25))

False


In [115]:
# Exercise 3.4: Primes b)
def is_prime(n):
    if n == 2 or n == 3:
        return True
    else:
        i = 1
        isCont = True
        while 6*i+1 <= n:
            if 6*i+1 == n or 6*i-1 == n:
                return True
            i += 1
        return False        
                
if __name__ == "__main__":
    print(is_prime(16))

False


In [116]:
# Exercise 3.4: Primes c)
def up_to_prime(number):
    for j in range(2, number):
        isPrime = True
        for i in range(2,number):
            if(j % i == 0 and j != i):
                isPrime = False
        if(isPrime == True):
                print(j)
        

if __name__ == "__main__":
    up_to_prime(12)

2
3
5
7
11


In [117]:
# Exercise 3.4: Primes d) Write a function that returns the first n primes.

def nPrimeNumbers(n):
    numberOfPrimes = 0
    num = 2
    while numberOfPrimes != n:
        isPrime = True
        for i in range(2,n):
            if(num % i == 0 and num != i):
                isPrime = False
        if(isPrime == True):
            print(num)
            numberOfPrimes +=1
        num += 1
             
if __name__ == "__main__":
    nPrimeNumbers(5)

2
3
5
7
11
